name: learn_bloc_crud
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '^3.5.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4

  #BloC
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  #Custom Repository
  user_repository:
    path: packages/user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
