name: post_repository
description: Dart package which manages the post.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.5.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  firebase_core: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

